package tests;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.Assert;
import org.testng.annotations.*;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;

import io.github.bonigarcia.wdm.WebDriverManager;

/*
 * This class has been generated by Selenium IDE after recording the login scenario on localhost for Swag Labs application.
 * The purpose is to show how to write a basic Selenium test case
 * The recording was exported as Java Selenium with JUnit, with the only changes:
 * 1. setting the package to test.ui
 * Adding in the setup the setting of the property "webdriver.chrome.driver" pointing to the absolute folder on my computer of the Chrome Web Driver.
 * So this has to be changed accordingly
 */
public class LoginBasicTest {


	private WebDriver driver;

	@BeforeTest
	public void setUp() throws MalformedURLException {
		String huburl = "http://localhost:4444/wd/hub";
		
		DesiredCapabilities cap = new DesiredCapabilities();
		
		cap.setPlatform(Platform.ANY);
		cap.setBrowserName("chrome");
		
		driver = new RemoteWebDriver(new URL(huburl), cap);
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
	}

	@AfterTest
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void login() {
		System.out.println("0. Start");

		System.out.println("1. Open target page");
		driver.get("https://www.saucedemo.com/");
		driver.manage().window().setSize(new Dimension(1350, 637));

		System.out.println("2. Insert username and password");

		System.out.println(" 2.1 Insert username");
		driver.findElement(By.id("login_credentials")).click();
		driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
		driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");

		System.out.println(" 2.1 Insert password");
		driver.findElement(By.cssSelector(".login_password")).click();
		driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
		driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");

		System.out.println("3. Click submit to perform login");
		driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();

		System.out.println("4. Verify login has been successfully executed");
		System.out.println(" 4.1 Page title is 'Swag Labs'");
		Assert.assertEquals(driver.getTitle(), "Swag Labs");

		System.out.println(" 4.2 Page url contains 'inventory'");
		Assert.assertEquals(driver.getCurrentUrl().contains("inventory"), true);

		// Pause the execution for 2 seconds to show the logged in page
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		System.out.println("5. End");
	}
}
